Added score & goals per user to GameResults.
PTS3-S34A/User-Interface pull request #28
Opened 2016-12-10 16:45 UTC by bras1223

2016-12-10 22:49 UTC, BeeHiveJava requested changes

2016-12-10 22:49 UTC, BeeHiveJava commented on Soccar [UI]/src/nl/soccar/ui/fx/controller/GameResultsFXMLController.java
> +                if (e.getType() == EventType.GOAL_BLUE && e.getPlayer().equals(p)) {
Equals methode werkt niet op Player. Gelieve e.getPlayer().getUsername().equals(p.getUsername()) te gebruiken.

2016-12-10 22:49 UTC, BeeHiveJava commented on Soccar [UI]/src/nl/soccar/ui/fx/controller/GameResultsFXMLController.java
> +        for (Player p : room.getTeamRed().getPlayers()) {
Equals methode werkt niet op Player. Gelieve e.getPlayer().getUsername().equals(p.getUsername()) te gebruiken.

2016-12-10 22:49 UTC, BeeHiveJava commented on Soccar [UI]/src/nl/soccar/ui/fx/controller/GameResultsFXMLController.java
> +                if (e.getType() == EventType.GOAL_BLUE && e.getPlayer().equals(p)) {
Ook is dit hele blok gedupliceerd. Gelieve een methode maken die een Team parameter neemt zodat je daar Team blue en Red in kan meegeven (2x aanroepen).

2016-12-10 22:49 UTC, BeeHiveJava commented on Soccar [UI]/src/nl/soccar/ui/fx/controller/GameResultsFXMLController.java
> +        for (Player p : room.getTeamRed().getPlayers()) {
Ook is dit hele blok gedupliceerd. Gelieve een methode maken die een Team parameter neemt zodat je daar Team blue en Red in kan meegeven (2x aanroepen).

2016-12-11 22:43 UTC, TehMessiah commented on Soccar [UI]/src/nl/soccar/ui/fx/controller/GameResultsFXMLController.java
> +    private int countGoalsUser(EventType type, Player p) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) Remove this unused method parameter "type". [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AS1172)

2016-12-11 22:43 UTC, TehMessiah commented
SonarQube analysis reported 1 issue
* ![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png) 1 major

Watch the comments in this conversation to review them.

2016-12-12 07:33 UTC, BeeHiveJava approved these changes

2016-12-12 07:33 UTC, merged